server:
  port: 8080

logging.level:
  com.backbase: INFO
  springframework.web.filter.CommonsRequestLoggingFilter: INFO
  org.apache.http: INFO

# API Registry client configuration
eureka:
  instance:
    metadata-map:
      public: true
      role: live
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    enabled: true

# Configure Internal JWT handler
sso:
  jwt:
    internal:
      signature:
        key:
          type: value
          value: JWTSecretKeyDontUseInProduction!
#          type: ENV
#          value: SIG_SECRET_KEY

# Spring health monitoring
management:
  health:
    jms:
      enabled: false
backbase:
  content:
    connector:
      google:
        projectId: prj-ABB-dev1-shared
        rootBucketName: dev-ekyc-nhs
        timeoutInMinutes: 15


